version: '3'

services:
  redis:
    container_name: node_redis
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  #   https://docs.docker.com/compose/wordpress/#define-the-project