version: '3'

services:

  redis:
    container_name: redis
    image: redis:latest
  mongo:
    container_name: mongo
    image: mongo
  node:
    build: .
    container_name: api
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: always
    links:
      - redis
      - mongo

volumes:
  node:

