version: '3'

services:
  node:
    container_name: node_api
    image: node:boron
    ports:
      - "3000"
  redis:
    container_name: node_redis
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
